Add Change Log file
cabotapp/cabot-alert-email pull request #9
Opened 2017-11-07 11:38 UTC by JeanFred

This follows the keep-a-changelog standard,
using `github-changelog-generator` as a base.

2017-11-07 11:39 UTC, JeanFred commented
The base was done using:
```
docker run -v $(pwd):/tmp -ti --entrypoint github_changelog_generator rubygem/github_changelog_generator --user cabotapp --project cabot-alert-email --pr-label '' --no-author 
```

2017-11-07 15:54 UTC, frankh commented on CHANGELOG.md
> +## [0.2](https://github.com/cabotapp/cabot-alert-email/tree/0.2) (2015-02-05)
ordering's a bit screwed up here

2017-11-07 15:55 UTC, frankh requested changes
Fix change log ordering between 1.2, 0.2 and 1.0.1

2017-11-09 12:27 UTC, JeanFred commented
Good catch, fixed.

2017-11-10 10:44 UTC, frankh approved these changes

2017-11-10 10:52 UTC, merged